### ISSUE TITLE
ti.end in the future issue with Tutorial 1.  (related to precision defined in /utils/time_utils.py)

### ISSUE THREAD

**Issue by Srceh** [IRC-SPHERE/HyperStream#22]
As I just reinstall my Ubuntu I tried to run Tutorial 1 again for a test.

The issue occurs in the (Executing a new interval) section, which I think is caused by the precision of utcnow() defined in hyperstream/utils/time_utils.py.

It is interesting I didn't have this issue in the past... 

For instance:

interval.end = datetime.datetime(2017, 8, 18, 9, 41, 14, 262064, tzinfo=<UTC>)
     utcnow() = datetime.datetime(2017, 8, 18, 9, 41, 14, 262000, tzinfo=<UTC>)

    137             if interval.end > utcnow():
    138                 print [interval.end, utcnow()]
--> 139                 raise ValueError("Calculated intervals should not be in the future")
    140 
    141         self._calculated_intervals = value

ValueError: Calculated intervals should not be in the future

**Comment by perellonieto** [comment]
To avoid all these problems, we should just change the time intervals of the tutorials to at least some minutes or hours in the past.

**Comment by tdiethe** [comment]
HyperStream is only millisecond precise, so this comparison should be changed to remove microseconds.

**Comment by tdiethe** [comment]
Should now be fixed with https://github.com/IRC-SPHERE/HyperStream/commit/fb58a388c5f5e844032987ac5e180263e9637519

Would be good if someone were to write a unit test to verify this.
