### ISSUE TITLE
Sources for tools/nodes should be dicts not lists

### ISSUE THREAD

**Issue by tdiethe** [IRC-SPHERE/HyperStream#7]
Would make it easier to check for errors, and remove special cases such as alignment_node and splitting_stream. However would require all tools to be rewritten.

**Comment by perellonieto** [comment]
I will help after I create the first tutorial that uses a source.

**Comment by tdiethe** [comment]
I think we came to the decision to close this one: it would be a huge change and potentially not backwards compatible with existing data.
